@startuml

Class ActiviteSoinAutorisee
Class AutreActiviteSoumiseAutorisation
Class ActiviteSoumiseReconnaissance
Class ActiviteSociale
Class ActiviteEnseignement
Class EquipementMaterielLourd
Class CapaciteActiviteExercee


@enduml