@startuml

Class BoiteLettreMSS
Class Diplome
Class PersonnePhysique
Class Adresse
Class Telecommunication
Class Horaire
Class Contact
Class Lieu
Class DivisionTerritoriale
Class Patientele
Class DiplomeEtat
Class DiplomeEtudeSpecialisee
Class FormationSpecialiseeTransversale
Class DESC1
Class DESC2
Class DiplomeEEE
Class DiplomeEES
Class DiplomeUniversitaire
Class CertificatEtudeSpeciale
Class Attestation
Class CapaciteDiplome
Class DiplomeDivers
Class AutreDiplomeObtenu
Class DiplomeDeuxiemeCycleNonQualifiant
Class LangueParlee
Class CoordonneeGeographique


@enduml