@startuml

Class PoleActivite {
}

Class StructureInterne {
}

Class UniteFonctionnelle {
}

Class OrganisationInterne {
  identifiantOI : Identifier [0..1]
  nomOI : string [0..1]
  typeOI : Coding [0..1]
  dateOuverture : date [0..1]
  dateFermeture : date [0..1]
  typeFermeture : Coding [0..1]
  datePrevisionnelleReouverture : date [0..1]
}

package "Structure" as Structure_part {
  Class EntiteGeographique
}

package "Offre opérationnelle" as Offre_opérationnelle_part {
  Class OffreOperationnelle
}

package "Agenda" as Agenda_part {
  Class Agenda
  Class RendezVous
}

OrganisationInterne "*" -- "1..*" EntiteGeographique
OrganisationInterne "*" -- "*" OrganisationInterne
OrganisationInterne "0..1" -- "1..*" OffreOperationnelle
OrganisationInterne "*" -- "*" Agenda
OrganisationInterne "*" -- "*" RendezVous

@enduml