@startuml

Class ExerciceProfessionnel {
  civiliteExercice : Coding [0..1]
  nomExercice : string [0..1]
  prenomExercice : string [0..1]
  profession : Coding [0..1]
  typeProfession : Coding [0..1]
  categorieProfessionnelle : Coding [0..1]
  dateEffetExercice : date [0..1]
  dateFinEffetExercice : date [0..1]
  departementPremierReferencementAE : Coding [0..1]
}

Class Professionnel {
  idPP : Identifier [0..1]
  typeIdNatPP : Coding [0..1]
  idNatPS : Identifier [0..1]
}

Class SavoirFaire {
  typeSavoirFaire : Coding [0..1]
  dateReconnaissance : date [0..1]
  dateAbandon : date [0..1]
}

Class SituationExercice {
  role : Coding [0..1]
  typeRole : Coding [0..1]
  modeExercice : Coding [0..1]
  numeroAM : Identifier [0..1]
  dateDebutActivite : date [0..1]
  dateFinActivite : date [0..1]
  genreActivite : Coding [0..1]
  motifFinActivite : Coding [0..1]
  statutHospitalier : Coding [0..1]
  sectionOrdrePharmacien : Coding [0..1]
  sousSectionOrdrePharmacien : Coding [0..1]
  typeActiviteLiberale : Coding [0..1]
  statutPSSSA : Coding [0..1]
}

Class SituationOperationnelle {
  identifiantSituationOperationnelle : Identifier [0..1]
  modeExerciceOffre : Coding [0..1]
  competenceSpecifique : Coding [0..*]
  secteurConventionnement : Coding [0..1]
  optionContratAccesAuxSoins : boolean [0..1]
  carteVitaleAcceptee : boolean [0..1]
}

Class InscriptionOrdre #LightBlue {
  ordre : Coding [0..1]
  dateDebutInscription : date [0..1]
  dateRadiation : date [0..1]
  statutInscription : Coding [0..1]
  conseilDepartemental : Coding [0..1]
}

Class AttributionParticuliere #LightBlue {
  attributionParticuliere : Coding [0..1]
  dateDebutReconnaissance : date [0..1]
  dateAbandon : date [0..1]
}

Class NiveauFormation #LightBlue {
  natureCycleFormation : Coding [0..1]
  niveauFormationAcquis : Coding [0..1]
  anneeUniversitaire : Coding [0..1]
  dateFin : date [0..1]
}

package "Dispositif d'authentification" as Dispositif_d'authentification_part {
  Class Certificat
  Class CarteProfessionnel
}

package "Dossier" as Dossier_part {
  Class NoteLiaison
}

package "Personne prise en charge" as Personne_prise_en_charge_part {
  Class Observation
  Class PersonnePriseCharge
}

package "Accord" as Accord_part {
  Class AutorisationExercice
}

package "Agenda" as Agenda_part {
  Class Agenda
  Class RendezVous
}

package "Structure" as Structure_part {
  Class EntiteGeographique
}

package "Offre opérationnelle" as Offre_opérationnelle_part {
  Class OffreOperationnelle
}

ExerciceProfessionnel "1" -- "*" SituationExercice
ExerciceProfessionnel "1" -- "*" SavoirFaire
ExerciceProfessionnel "*" -- "1" Professionnel
ExerciceProfessionnel "1" -- "*" SituationOperationnelle
ExerciceProfessionnel "0..1" -- "*" Certificat
ExerciceProfessionnel "1" -- "*" CarteProfessionnel
Professionnel "0..1" -- "*" NoteLiaison
Professionnel "0..1" -- "*" Observation
Professionnel "*" -- "*" PersonnePriseCharge
Professionnel "0..1" -- "*" AutorisationExercice
Professionnel "*" -- "*" Agenda
Professionnel "*" -- "*" RendezVous
SituationExercice "*" -- "0..1" EntiteGeographique
SituationOperationnelle "*" -- "1" OffreOperationnelle
ExerciceProfessionnel --> InscriptionOrdre : 0..*
ExerciceProfessionnel --> AttributionParticuliere : 0..1
ExerciceProfessionnel --> NiveauFormation : 0..*

@enduml