@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

' Le diagramme n'est pas correct, il a été ajouté à titre d'exemple

' === Classes principales ===
class Professionnel {
  +idPP : Identifiant [0..1]
  +idNat_PP : Identifiant [0..1]
  +personne : PersonnePhysique [0..1]
  +diplomeObtenu : Diplome [1]
  +adresseCorrespondance : Adresse [1]
  +telecommunication : Telecommunication [*]
  +boiteLettreMSS : BoiteLettreMSS [*]
  +metadonnee : Metadonnee [0..1]
}

class ExerciceProfessionnel {
  +civiliteExercice : Code [0..1]
  +nomExercice : Texte [0..1]
  +prenomExercice : Texte [0..1]
  +typeProfession : Code [1]
  +categorieProfession : Code [0..1]
  +codeProfession : Code [1]
  +dateEffetExercice : Date [0..1]
  +dateFinExercice : Date [0..1]
  +departementRemp : Code [0..1]
  +boiteLettreMSS : BoiteLettreMSS [*]
  +metadonnee : Metadonnee [0..1]
}

class SituationExercice {
  +role : Code [0..1]
  +typeRole : Code [0..1]
  +modeExercice : Code [0..1]
  +numeroAM : Identifiant [0..1]
  +dateDebutActivite : Date [0..1]
  +dateFinActivite : Date [0..1]
  +sectionOrdre : Code [0..1]
  +sousSectionOrdre : Code [0..1]
  +typeActivitePrincipale : Code [0..1]
  +statutPS_SSA : Code [0..1]
  +telecommunication : Telecommunication [*]
  +adresseSE : Adresse [1]
  +boiteLettreMSS : BoiteLettreMSS [*]
  +metadonnee : Metadonnee [0..1]
}

class SituationOperationnelle {
  +identifiantSituationOperationnelle : Identifiant [0..1]
  +modeExerciceOC : Code [0..1]
  +competenceSpecifique : Code [*]
  +precisionHoraire : Horaire [0..1]
  +secteurConventionnement : Code [0..1]
  +optionContractuelleSousAncienneIndicateur : Code [0..1]
  +carteVitaleAcceptee : Indicateur [0..1]
  +telecommunication : Telecommunication [0..1]
  +metadonnee : Metadonnee [0..1]
}

Package "Offre opérationnelle" {
    class OffreOperationnelle
}

Package "Dispositif d'authentification" {
    class CarteProfessionnel {}
    class Certificat {}
}

Package "Dossier" {
    class NoteLiaison
}


Package "Structure" {
    class EntiteGeographique
}

Package "Personne prise en charge" {
    class PersonnePriseCharge {}
}

Package "Accord" {
    class AutorisationExercice
}


Package "Agenda" {
    class RendezVous {}
    class Agenda {}
}

class InscriptionOrdre {
  +ordre : Code [0..1]
  +dateDebutInscription : Date [0..1]
  +dateRadiation : Date [0..1]
  +statutInscription : Code [0..1]
  +conseilDepartemental : Code [0..1]
  +metadonnee : Metadonnee [0..1]
}

class SavoirFaire {
  +typeSavoirFaire : Code [0..1]
  +dateReconnaissance : Date [0..1]
  +dateAbandon : Date [0..1]
  +metadonnee : Metadonnee [0..1]
}

class AttributionParticuliere {
  +attributionParticuliere : Code [0..1]
  +dateDebutReconnaissance : Date [0..1]
  +dateAbandon : Date [0..1]
  +metadonnee : Metadonnee [0..1]
}

class NiveauFormation {
  +diplome : Diplome [0..1]
  +natureCycleFormation : Code [0..1]
  +niveauFormationAcquis : Code [0..1]
  +anneeUniversitaire : Code [0..1]
  +dateFin : Date [0..1]
  +metadonnee : Metadonnee [0..1]
}

' === Relations ===

Professionnel "1" -- "*" ExerciceProfessionnel
Professionnel "*" -- "*" Agenda
Professionnel "1" -- "*" NoteLiaison
Professionnel "1" -- "*" AutorisationExercice
Professionnel "1" -- "*" PersonnePriseCharge

ExerciceProfessionnel "1" -- "*" InscriptionOrdre
ExerciceProfessionnel "1" -- "*" SavoirFaire
ExerciceProfessionnel "1" -- "*" AttributionParticuliere
ExerciceProfessionnel "1" -- "*" NiveauFormation


ExerciceProfessionnel "0..1" -- "*" CarteProfessionnel
ExerciceProfessionnel "1" -- "*" Certificat

ExerciceProfessionnel "1" -- "*" SituationExercice
ExerciceProfessionnel "1" -- "*" SituationOperationnelle


SituationOperationnelle "*" -- "1" OffreOperationnelle
SituationExercice "*" -- "0..1" EntiteGeographique
 

@enduml
