@startuml

Class ExerciceProfessionnel
Class Professionnel
Class SavoirFaire
Class SituationExercice
Class SituationOperationnelle
Class Specialite
Class SurspecialiteTransversale
Class Competence
Class CompetenceMetier
Class CompetenceExclusive
Class OrientationParticuliere
Class CapaciteSavoirfaire
Class QualificationPAC
Class FonctionQualifiee
Class DESCNonQualifiant
Class DroitExerciceComplementaire

ExerciceProfessionnel --> Professionnel : 1..1
SavoirFaire --> ExerciceProfessionnel : 1..1
SituationExercice --> ExerciceProfessionnel : 1..1
SituationOperationnelle --> ExerciceProfessionnel : 1..1

@enduml