@startuml

Class EntiteJuridique {
  numFINESS : Identifier [0..1]
  numSiren : Identifier [0..1]
  idNatStruct : Identifier [0..1]
  identifiantEJ : Identifier [0..1]
  typeIdNatStruct : Coding [0..1]
  numeroTVAIntracommunautaire : Identifier [0..1]
  numeroSRN : Identifier [0..*]
  raisonSociale : string [0..1]
  raisonSocialeLongue : string [0..1]
  complementRaisonSociale : string [0..1]
  statutJuridique : Coding [0..1]
  agregatStatutJuridiqueNiv1 : Coding [0..1]
  agregatStatutJuridiqueNiv2 : Coding [0..1]
  agregatStatutJuridiqueNiv3 : Coding [0..1]
  codeAPEN : Coding [0..1]
  dateCreation : date [0..1]
  dateModificationSiren : date [0..1]
  origineModificationSIREN : string [0..1]
  dateFermeture : date [0..1]
  typeFermeture : Coding [0..1]
}

Class EntiteGeographique {
  numFINESS : Identifier [0..1]
  numSiret : Identifier [0..1]
  identifiantEG : Identifier [0..1]
  idNatStruct : Identifier [0..1]
  typeIdNatStruct : Coding [0..1]
  numeroEducationNationale : string [0..1]
  nomOperationnel : string [0..1]
  denominationEG : string [0..1]
  denominationEGLongue : string [0..1]
  complementDenominationEG : string [0..1]
  champActivite : Coding [0..*]
  typeEtablissement : string [0..1]
  etablissementPrincipal : Identifier [0..1]
  secteurActivite : Coding [0..1]
  categorieEtablissement : Coding [0..1]
  agregatCategorieEtablissementNiv1 : Coding [0..1]
  agregatCategorieEtablissementNiv2 : Coding [0..1]
  agregatCategorieEtablissementNiv3 : Coding [0..1]
  codeAPET : Coding [0..1]
  modeFixationTarif : Coding [0..1]
  modaliteParticipationSPH : Coding [0..1]
  natureEtablissement : string [0..1]
  aideFinanciere : Coding [0..*]
  habilitationSoinSansConsentement : boolean [0..1]
  hebergementFamille : boolean [0..1]
  dateModificationSIRET : date [0..1]
  origineModificationSIRET : string [0..1]
  actif : boolean [0..1]
  dateOuverture : date [0..1]
  dateCaducite : date [0..1]
  constatCaducite : boolean [0..1]
  dateFermeture : date [0..1]
  typeFermeture : Coding [0..1]
  dateAutorisation : date [0..1]
  accessibiliteLieu : Coding [0..1]
  zonePoser : boolean [0..1]
  niveauRecoursORSAN : Coding [0..1]
  venteLigneURL : string [0..1]
  nbPlaceAideSocialeTemporaire : integer [0..1]
  nbPlaceAideSocialePermanent : integer [0..1]
  commentaire : string [0..1]
}

EntiteGeographique --> EntiteJuridique : 1..1

@enduml