@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class Adresse{

             Address.use => [None..None]
             Address.city => [None..None]
             Address.state => [None..None]
             Address.postalCode => [None..None]
             Address.country => [None..None]
        } 

        class BoiteLettreMSS{

             BoiteLettreMSS => [None..None]
             BoiteLettreMSS.adresseMSS => [0..1]
             BoiteLettreMSS.typeBAL => [0..1]
             BoiteLettreMSS.description => [0..1]
             BoiteLettreMSS.responsable => [0..1]
             BoiteLettreMSS.serviceRattachement => [0..1]
             BoiteLettreMSS.telephone => [0..1]
             BoiteLettreMSS.dematerialisation => [0..1]
             BoiteLettreMSS.listeRouge => [0..1]
        } 

        class CapaciteSavoirfaire{

             CapaciteSavoirfaire => [None..None]
             CapaciteSavoirfaire.capaciteSavoirFaire => [0..1]
        } 

        class Competence{

             Competence => [None..None]
             Competence.competence => [0..1]
        } 

        class CompetenceExclusive{

             CompetenceExclusive => [None..None]
             CompetenceExclusive.competenceExclusive => [0..1]
        } 

        class CompetenceMetier{

             CompetenceMetier => [None..None]
             CompetenceMetier.competenceMetier => [0..1]
        } 

        class DESCNonQualifiant{

             DESCNonQualifiant => [None..None]
             DESCNonQualifiant.DESCNonQualifiant => [0..1]
        } 

        class Diplome{

             Diplome => [None..None]
             Diplome.typeDiplome => [0..1]
             Diplome.lieuFormation => [0..1]
             Diplome.dateDiplome => [0..1]
             Diplome.numeroDiplome => [0..1]
        } 

        class DroitExerciceComplementaire{

             DroitExerciceComplementaire => [None..None]
             DroitExerciceComplementaire.droitExerciceComplementaire => [0..1]
        } 

        class ExerciceProfessionnel{

             ExerciceProfessionnel => [None..None]
             ExerciceProfessionnel.civiliteExercice => [0..1]
             ExerciceProfessionnel.nomExercice => [0..1]
             ExerciceProfessionnel.prenomExercice => [0..1]
             ExerciceProfessionnel.profession => [0..1]
             ExerciceProfessionnel.typeProfession => [0..1]
             ExerciceProfessionnel.categorieProfessionnelle => [0..1]
             ExerciceProfessionnel.dateEffetExercice => [0..1]
             ExerciceProfessionnel.dateFinEffetExercice => [0..1]
             ExerciceProfessionnel.departementPremierReferencementAE => [0..1]
             ExerciceProfessionnel.boiteLettresMSS => [0..*]
             ExerciceProfessionnel.InscriptionOrdre => [0..*]
             ExerciceProfessionnel.InscriptionOrdre.ordre => [0..1]
             ExerciceProfessionnel.InscriptionOrdre.dateDebutInscription => [0..1]
             ExerciceProfessionnel.InscriptionOrdre.dateRadiation => [0..1]
             ExerciceProfessionnel.InscriptionOrdre.statutInscription => [0..1]
             ExerciceProfessionnel.InscriptionOrdre.conseilDepartemental => [0..1]
             ExerciceProfessionnel.SavoirFaire => [0..*]
             ExerciceProfessionnel.SavoirFaire.typeSavoirFaire => [0..1]
             ExerciceProfessionnel.SavoirFaire.dateReconnaissance => [0..1]
             ExerciceProfessionnel.SavoirFaire.dateAbandon => [0..1]
             ExerciceProfessionnel.AttributionParticuliere => [0..*]
             ExerciceProfessionnel.AttributionParticuliere.attributionParticuliere => [0..1]
             ExerciceProfessionnel.AttributionParticuliere.dateDebutReconnaissance => [0..1]
             ExerciceProfessionnel.AttributionParticuliere.dateAbandon => [0..1]
             ExerciceProfessionnel.NiveauFormation => [0..*]
             ExerciceProfessionnel.NiveauFormation.diplome => [0..1]
             ExerciceProfessionnel.NiveauFormation.natureCycleFormation => [0..1]
             ExerciceProfessionnel.NiveauFormation.niveauFormationAcquis => [0..1]
             ExerciceProfessionnel.NiveauFormation.anneeUniversitaire => [0..1]
             ExerciceProfessionnel.NiveauFormation.dateFin => [0..1]
        } 

        class FonctionQualifiee{

             FonctionQualifiee => [None..None]
             FonctionQualifiee.fonctionQualifiee => [0..1]
        } 

        class Horaire{

             Horaire => [None..None]
             Horaire.idPlageHoraire => [0..1]
             Horaire.typePlageHoraire => [0..1]
             Horaire.ouvertureFermeture => [0..1]
             Horaire.jourSemaine => [0..1]
             Horaire.heureDebut => [0..1]
             Horaire.heureFin => [0..1]
             Horaire.frequencePlageHoraire => [0..1]
             Horaire.debutDateEffective => [0..1]
             Horaire.finDateEffective => [0..1]
             Horaire.dateDeclarationPlageHoraire => [0..1]
             Horaire.commentaire => [0..*]
        } 

        class LangueParlee{

             LangueParlee => [None..None]
             LangueParlee.langueParlee => [0..1]
             LangueParlee.dateFin => [0..1]
        } 

        class OrientationParticuliere{

             OrientationParticuliere => [None..None]
             OrientationParticuliere.orientationParticuliere => [0..1]
        } 

        class PersonnePhysique{

             PersonnePhysique => [None..None]
             PersonnePhysique.civilite => [0..1]
             PersonnePhysique.nomFamille => [0..1]
             PersonnePhysique.nomUsage => [0..1]
             PersonnePhysique.prenom => [0..*]
             PersonnePhysique.prenomUsuel => [0..1]
             PersonnePhysique.pseudonyme => [0..1]
             PersonnePhysique.surnom => [0..1]
             PersonnePhysique.sexeAdministratif => [0..1]
             PersonnePhysique.sexe => [0..1]
             PersonnePhysique.langueParlee => [0..*]
             PersonnePhysique.situationFamiliale => [0..1]
             PersonnePhysique.dateNaissance => [0..1]
             PersonnePhysique.dateDeces => [0..1]
             PersonnePhysique.communeNaissance => [0..1]
             PersonnePhysique.departementNaissance => [0..1]
             PersonnePhysique.paysNaissance => [0..1]
             PersonnePhysique.lieuNaissance => [0..1]
             PersonnePhysique.statutEtatCivil => [0..1]
             PersonnePhysique.dateStatutEtatCivil => [0..1]
             PersonnePhysique.dateAcquisitionNatFR => [0..1]
             PersonnePhysique.paysNationalite => [0..1]
             PersonnePhysique.paysResidence => [0..1]
             PersonnePhysique.professionCategorieSocioProfessionnelle => [0..1]
             PersonnePhysique.causeMortalite => [0..1]
             PersonnePhysique.tailleCorporelle => [0..1]
             PersonnePhysique.poidsCorporel => [0..1]
             PersonnePhysique.surfaceCorporelle => [0..1]
             PersonnePhysique.indiceMasseCorporelle => [0..1]
        } 

        class Professionnel{

             Professionnel => [None..None]
             Professionnel.idPP => [0..1]
             Professionnel.typeIdNatPP => [0..1]
             Professionnel.idNatPS => [0..1]
             Professionnel.personne => [0..1]
             Professionnel.diplomeObtenu => [0..*]
             Professionnel.adresseCorrespondance => [0..*]
             Professionnel.telecommunication => [0..*]
             Professionnel.boiteLettresMSS => [0..*]
        } 

        class QualificationPAC{

             QualificationPAC => [None..None]
             QualificationPAC.qualificationPAC => [0..1]
        } 

        class SituationExercice{

             SituationExercice => [None..None]
             SituationExercice.role => [0..1]
             SituationExercice.typeRole => [0..1]
             SituationExercice.modeExercice => [0..1]
             SituationExercice.numeroAM => [0..1]
             SituationExercice.dateDebutActivite => [0..1]
             SituationExercice.dateFinActivite => [0..1]
             SituationExercice.genreActivite => [0..1]
             SituationExercice.motifFinActivite => [0..1]
             SituationExercice.statutHospitalier => [0..1]
             SituationExercice.sectionOrdrePharmacien => [0..1]
             SituationExercice.sousSectionOrdrePharmacien => [0..1]
             SituationExercice.typeActiviteLiberale => [0..1]
             SituationExercice.statutPSSSA => [0..1]
             SituationExercice.telecommunication => [0..*]
             SituationExercice.adresseSE => [0..*]
             SituationExercice.boiteLettresMSS => [0..*]
        } 

        class SituationOperationnelle{

             SituationOperationnelle => [None..None]
             SituationOperationnelle.identifiantSituationOperationnelle => [0..1]
             SituationOperationnelle.modeExerciceOffre => [0..1]
             SituationOperationnelle.competenceSpecifique => [0..*]
             SituationOperationnelle.precisionHoraire => [0..1]
             SituationOperationnelle.secteurConventionnement => [0..1]
             SituationOperationnelle.optionContratAccesAuxSoins => [0..1]
             SituationOperationnelle.carteVitaleAcceptee => [0..1]
             SituationOperationnelle.telecommunication => [0..1]
        } 

        class Specialite{

             Specialite => [None..None]
             Specialite.specialite => [0..1]
        } 

        class SurspecialiteTransversale{

             SurspecialiteTransversale => [None..None]
             SurspecialiteTransversale.surspecialiteTransversale => [0..1]
        } 

        class Telecommunication{

             ContactPoint.extension:TypeMessagerie => <&plus>[0..1]
             ContactPoint.extension:NiveauConfidentialite => <&plus>[0..1]
             ContactPoint.system => [None..None]
             ContactPoint.value => [None..None]
             ContactPoint.use => [None..None]
         }

     }
     package extension #paleturquoise {

     Telecommunication -[#black,dashed,thickness=2]-> TypeMessagerie
     Telecommunication -[#black,dashed,thickness=2]-> NiveauConfidentialite

        class NiveauConfidentialite{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class TypeMessagerie{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
         }
     }
     package valueset #PaleVioletRed{

        class TypebalVs  

     BoiteLettreMSS -[#black,dotted,thickness=2]-> TypebalVs

        class CapacitesavoirfaireVs  

     CapaciteSavoirfaire -[#black,dotted,thickness=2]-> CapacitesavoirfaireVs

        class CompetenceVs  

     Competence -[#black,dotted,thickness=2]-> CompetenceVs

        class CompetenceexclusiveVs  

     CompetenceExclusive -[#black,dotted,thickness=2]-> CompetenceexclusiveVs

        class EnsemblesavoirfaireCisisVs  

     CompetenceMetier -[#black,dotted,thickness=2]-> EnsemblesavoirfaireCisisVs

        class DescnonqualifiantVs  

     DESCNonQualifiant -[#black,dotted,thickness=2]-> DescnonqualifiantVs

        class TypediplomeVs  

     Diplome -[#black,dotted,thickness=2]-> TypediplomeVs

        class LieuformationVs  

     Diplome -[#black,dotted,thickness=2]-> LieuformationVs

        class DroitexercicecomplementaireVs  

     DroitExerciceComplementaire -[#black,dotted,thickness=2]-> DroitexercicecomplementaireVs

        class CiviliteexerciceVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> CiviliteexerciceVs

        class ProfessionVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> ProfessionVs

        class TypeprofessionVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> TypeprofessionVs

        class CategorieprofessionnelleVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> CategorieprofessionnelleVs

        class DepartementomVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> DepartementomVs

        class OrdreVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> OrdreVs

        class StatutinscriptionVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> StatutinscriptionVs

        class DepartementomVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> DepartementomVs

        class TypesavoirfaireVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> TypesavoirfaireVs

        class AttributionparticuliereVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> AttributionparticuliereVs

        class NatcycleformVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> NatcycleformVs

        class NiveauformacquisVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> NiveauformacquisVs

        class AnneeuniversitaireVs  

     ExerciceProfessionnel -[#black,dotted,thickness=2]-> AnneeuniversitaireVs

        class FonctionqualifieeVs  

     FonctionQualifiee -[#black,dotted,thickness=2]-> FonctionqualifieeVs

        class TypehoraireVs  

     Horaire -[#black,dotted,thickness=2]-> TypehoraireVs

        class LangueVs  

     LangueParlee -[#black,dotted,thickness=2]-> LangueVs

        class NiveauConfidentialiteVs  

     NiveauConfidentialite -[#black,dotted,thickness=2]-> NiveauConfidentialiteVs

        class OrientationparticuliereVs  

     OrientationParticuliere -[#black,dotted,thickness=2]-> OrientationparticuliereVs

        class CiviliteVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> CiviliteVs

        class SexeadministratifVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> SexeadministratifVs

        class SexeVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> SexeVs

        class CommuneomVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> CommuneomVs

        class DepartementomVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> DepartementomVs

        class PaysnaissanceVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> PaysnaissanceVs

        class LieunaissanceVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> LieunaissanceVs

        class StatutetatcivilVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> StatutetatcivilVs

        class PaysnationaliteVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> PaysnationaliteVs

        class PaysVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> PaysVs

        class ProfessioncategoriesocioprofessionnelleVs  

     PersonnePhysique -[#black,dotted,thickness=2]-> ProfessioncategoriesocioprofessionnelleVs

        class TypeidentifiantpersonneVs  

     Professionnel -[#black,dotted,thickness=2]-> TypeidentifiantpersonneVs

        class QualificationpacVs  

     QualificationPAC -[#black,dotted,thickness=2]-> QualificationpacVs

        class RoleVs  

     SituationExercice -[#black,dotted,thickness=2]-> RoleVs

        class TyperoleVs  

     SituationExercice -[#black,dotted,thickness=2]-> TyperoleVs

        class ModeexerciceVs  

     SituationExercice -[#black,dotted,thickness=2]-> ModeexerciceVs

        class GenreactiviteVs  

     SituationExercice -[#black,dotted,thickness=2]-> GenreactiviteVs

        class MotiffinactiviteVs  

     SituationExercice -[#black,dotted,thickness=2]-> MotiffinactiviteVs

        class StatuthospitalierVs  

     SituationExercice -[#black,dotted,thickness=2]-> StatuthospitalierVs

        class SectiontableaucnopVs  

     SituationExercice -[#black,dotted,thickness=2]-> SectiontableaucnopVs

        class SoussectiontableaucnopVs  

     SituationExercice -[#black,dotted,thickness=2]-> SoussectiontableaucnopVs

        class TypeactiviteliberaleVs  

     SituationExercice -[#black,dotted,thickness=2]-> TypeactiviteliberaleVs

        class StatutprofessionnelssaVs  

     SituationExercice -[#black,dotted,thickness=2]-> StatutprofessionnelssaVs

        class ModeexerciceVs  

     SituationOperationnelle -[#black,dotted,thickness=2]-> ModeexerciceVs

        class CompetencespecifiqueVs  

     SituationOperationnelle -[#black,dotted,thickness=2]-> CompetencespecifiqueVs

        class CnamamelisecteurconventionnementVs  

     SituationOperationnelle -[#black,dotted,thickness=2]-> CnamamelisecteurconventionnementVs

        class SpecialiteVs  

     Specialite -[#black,dotted,thickness=2]-> SpecialiteVs

        class SurspecialitetransversaleVs  

     SurspecialiteTransversale -[#black,dotted,thickness=2]-> SurspecialitetransversaleVs

        class TypeMessagerieVs  

     TypeMessagerie -[#black,dotted,thickness=2]-> TypeMessagerieVs
       }

package "Ressources de base" #palegreen {

 class "Address" as  classdd7bf230fde8d4836917806aff6a6b27 

    classdd7bf230fde8d4836917806aff6a6b27 --> Adresse

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> BoiteLettreMSS

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> CapaciteSavoirfaire

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Competence

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> CompetenceExclusive

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> CompetenceMetier

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> DESCNonQualifiant

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Diplome

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> DroitExerciceComplementaire

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ExerciceProfessionnel

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> FonctionQualifiee

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Horaire

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> LangueParlee

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> OrientationParticuliere

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> PersonnePhysique

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Professionnel

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> QualificationPAC

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SituationExercice

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SituationOperationnelle

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Specialite

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SurspecialiteTransversale

 class "ContactPoint" as  class1a8de90955ed09d082aa583fa10a342e 

    class1a8de90955ed09d082aa583fa10a342e --> Telecommunication
}
@enduml