Logical: SituationExercice
Id: SituationExercice
Title: "SituationExercice"
* ^status = #draft
* . ^short = " Caractéristiques de l'exercice d’un professionnel pendant une période déterminée et dans une structure déterminée (à l'exception des remplaçants).Synonymes : Activité (RPPS)."
* . ^definition = " Caractéristiques de l'exercice d’un professionnel pendant une période déterminée et dans une structure déterminée (à l'exception des remplaçants).Synonymes : Activité (RPPS)."
* role 0..1 Coding " Rôle du professionnel au sein de la structure d’exercice. Par exemple, ** Titulaire de cabinet;** Titulaire d’officine;** Médecin scolaire;** etc.Synonyme : fonction" " Rôle du professionnel au sein de la structure d’exercice. Par exemple, ** Titulaire de cabinet;** Titulaire d’officine;** Médecin scolaire;** etc.Synonyme : fonction"
* role from https://interop.esante.gouv.fr/ig/fhir/mos/ValueSet/role-vs (preferred)
* typeRole 0..1 Coding " Indique le type de rôle du professionnel au sein de la structure d’exercice.Synonyme : typeFonction" " Indique le type de rôle du professionnel au sein de la structure d’exercice.Synonyme : typeFonction"
* typeRole from https://interop.esante.gouv.fr/ig/fhir/mos/ValueSet/typeRole-vs (preferred)
* modeExercice 0..1 Coding " Le mode d'exercice décrit selon quelle modalité une activité est exercée au regard de l'organisation de la rétribution du professionnel.Exemples : ** Libéral;** Salarié;** Bénévole.Les valeurs de ce code sont répertoriées dans la nomenclature CodeSystem-TRE-R23-ModeExercice." " Le mode d'exercice décrit selon quelle modalité une activité est exercée au regard de l'organisation de la rétribution du professionnel.Exemples : ** Libéral;** Salarié;** Bénévole.Les valeurs de ce code sont répertoriées dans la nomenclature CodeSystem-TRE-R23-ModeExercice."
* modeExercice from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R23-ModeExercice?vs (preferred)
* numeroAM 0..1 Identifier " Identifiant d’activité, propre à l’Assurance Maladie. Cet identifiant est attribué lors de l’enregistrement de l’activité par l’Assurance Maladie. Un professionnel a autant de numéros AM que d’activités enregistrées à l’Assurance Maladie. Cet identifiant d’activité est utilisé pour la facturation à l’Assurance Maladie. Sa diffusion est restreinte aux entités choisies par l’Assurance Maladie.Format : 9 caractères numériques généralement identiques au n°ADELI ou pseudo ADELI du professionnel pour sa première activité." " Identifiant d’activité, propre à l’Assurance Maladie. Cet identifiant est attribué lors de l’enregistrement de l’activité par l’Assurance Maladie. Un professionnel a autant de numéros AM que d’activités enregistrées à l’Assurance Maladie. Cet identifiant d’activité est utilisé pour la facturation à l’Assurance Maladie. Sa diffusion est restreinte aux entités choisies par l’Assurance Maladie.Format : 9 caractères numériques généralement identiques au n°ADELI ou pseudo ADELI du professionnel pour sa première activité."
* dateDebutActivite 0..1 date " Date de début de l’activité correspondant à la date d’installation en cabinet ou à la date d’embauche du salarié, etc." " Date de début de l’activité correspondant à la date d’installation en cabinet ou à la date d’embauche du salarié, etc."
* dateFinActivite 0..1 date " Date de fin de l’activité." " Date de fin de l’activité."
* genreActivite 0..1 Coding " Le genre d'activité identifie les activités qui nécessitent l’application de règles de gestion spécifiques, par exemple, activité standard de soins ou de pharmacien, activité non soignante, activité non médicale, etc." " Le genre d'activité identifie les activités qui nécessitent l’application de règles de gestion spécifiques, par exemple, activité standard de soins ou de pharmacien, activité non soignante, activité non médicale, etc."
* genreActivite from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R22-GenreActivite?vs (preferred)
* motifFinActivite 0..1 Coding " Motif de fin d'activité, par exemple:** Décès;** Retraite libérale;** Changement de profession;** etc." " Motif de fin d'activité, par exemple:** Décès;** Retraite libérale;** Changement de profession;** etc."
* motifFinActivite from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R25-MotifFinActivite?vs (preferred)
* statutHospitalier 0..1 Coding " Statut hospitalier dans le cas d’une activité exercée en établissement public de santé, par exemple:** Professeur des universités - praticien hospitalier (PU-PH);** Assistant hospitalier universitaire (AHU);** etc." " Statut hospitalier dans le cas d’une activité exercée en établissement public de santé, par exemple:** Professeur des universités - praticien hospitalier (PU-PH);** Assistant hospitalier universitaire (AHU);** etc."
* statutHospitalier from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R32-StatutHospitalier?vs (preferred)
* sectionOrdrePharmacien 0..1 Coding " Section du tableau de l’Ordre des pharmaciens, par exemple:** Pharmacien titulaire d’officine;** Pharmacien biologiste;** etc." " Section du tableau de l’Ordre des pharmaciens, par exemple:** Pharmacien titulaire d’officine;** Pharmacien biologiste;** etc."
* sectionOrdrePharmacien from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R06-SectionTableauCNOP?vs (preferred)
* sousSectionOrdrePharmacien 0..1 Coding " Sous-section ou à défaut section du tableau de l’Ordre des pharmaciens." " Sous-section ou à défaut section du tableau de l’Ordre des pharmaciens."
* sousSectionOrdrePharmacien from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-G05-SousSectionTableauCNOP?vs (preferred)
* typeActiviteLiberale 0..1 Coding " Type d’activité libérale, par exemple:** Cabinet;** Secteur privé à l'hôpital;** etc." " Type d’activité libérale, par exemple:** Cabinet;** Secteur privé à l'hôpital;** etc."
* typeActiviteLiberale from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R24-TypeActiviteLiberale?vs (preferred)
* statutPSSSA 0..1 Coding " Statut du professionnel du Service de santé des armées, par exemple:** Praticien certifié;** Praticien confirmé;** etc." " Statut du professionnel du Service de santé des armées, par exemple:** Praticien certifié;** Praticien confirmé;** etc."
* statutPSSSA from https://interop.esante.gouv.fr/terminologies/CodeSystem-TRE-R34-StatutProfessionnelSSA?vs (preferred)
* telecommunication 0..* https://interop.esante.gouv.fr/ig/fhir/mos/StructureDefinition/Telecommunication " Adresse(s) de télécommunication (numéro de téléphone, adresse email, URL, etc.) rattachée(s) à la situation d'exercice." " Adresse(s) de télécommunication (numéro de téléphone, adresse email, URL, etc.) rattachée(s) à la situation d'exercice."
* adresseSE 0..* https://interop.esante.gouv.fr/ig/fhir/mos/StructureDefinition/Adresse " Adresse(s) géopostale(s) rattachée(s) à la situation d'exercice." " Adresse(s) géopostale(s) rattachée(s) à la situation d'exercice."
* boiteLettresMSS 0..* https://interop.esante.gouv.fr/ig/fhir/mos/StructureDefinition/BoiteLettreMSS " Boîte(s) aux lettres du service de messagerie sécurisée de santé (MSS) rattachée(s) à la situation d'exercice." " Boîte(s) aux lettres du service de messagerie sécurisée de santé (MSS) rattachée(s) à la situation d'exercice."