Logical: ActiviteEnseignement
Parent: $Base
Id: ActiviteEnseignement
Title: "ActiviteEnseignement"
Description: "Les activités d’enseignement aux professions sanitaires et sociales sont enregistrées dans FINESS et rattachées aux établissements de formation (EG). Le périmètre comprend les formations sanitaires et sociales préparant à un diplôme d’état délivré par l’administration sanitaire et sociale. Sont exclues les formations aux professions médicales préparées en université, hormis les formations et écoles de sages-femmes.Ces formations sont soumises à un arrêté d’agrément de la Région."
* ^status = #draft
* . ^short = "Les activités d’enseignement aux professions sanitaires et sociales sont enregistrées dans FINESS et rattachées aux établissements de formation (EG). Le périmètre comprend les formations sanitaires et sociales préparant à un diplôme d’état délivré par l’administration sanitaire et sociale. Sont exclues les formations aux professions médicales préparées en université, hormis les formations et écoles de sages-femmes.Ces formations sont soumises à un arrêté d’agrément de la Région."
* . ^definition = "Les activités d’enseignement aux professions sanitaires et sociales sont enregistrées dans FINESS et rattachées aux établissements de formation (EG). Le périmètre comprend les formations sanitaires et sociales préparant à un diplôme d’état délivré par l’administration sanitaire et sociale. Sont exclues les formations aux professions médicales préparées en université, hormis les formations et écoles de sages-femmes.Ces formations sont soumises à un arrêté d’agrément de la Région."
* agregatDisciplineEnseignementNiv1 0..1 Coding "Agrégat de discipline d'enseignement de niveau 1. L'agrégat de niveau 1 représente des regroupements d'agrégat de niveau 2." "Agrégat de discipline d'enseignement de niveau 1. L'agrégat de niveau 1 représente des regroupements d'agrégat de niveau 2."
* agregatDisciplineEnseignementNiv1 from https://mos.esante.gouv.fr/NOS/TRE_R295-AgregatDisciplineEnseignNiv1/FHIR/TRE-R295-AgregatDisciplineEnseignNiv1?vs (preferred)
* agregatDisciplineEnseignementNiv2 0..1 Coding "Agrégat de discipline d'enseignement de niveau 2. L'agrégat de niveau 2 représente des regroupements d'agrégat de niveau 3." "Agrégat de discipline d'enseignement de niveau 2. L'agrégat de niveau 2 représente des regroupements d'agrégat de niveau 3."
* agregatDisciplineEnseignementNiv2 from https://mos.esante.gouv.fr/NOS/TRE_R296-AgregatDisciplineEnseignNiv2/FHIR/TRE-R296-AgregatDisciplineEnseignNiv2?vs (preferred)
* agregatDisciplineEnseignementNiv3 0..1 Coding "Agrégat de discipline d'enseignement de niveau 3. L'agrégat de niveau 3 représente des regroupements de disciplines d'équipement." "Agrégat de discipline d'enseignement de niveau 3. L'agrégat de niveau 3 représente des regroupements de disciplines d'équipement."
* agregatDisciplineEnseignementNiv3 from https://mos.esante.gouv.fr/NOS/TRE_R297-AgregatDisciplineEnseignNiv3/FHIR/TRE-R297-AgregatDisciplineEnseignNiv3?vs (preferred)
* disciplineEnseignement 0..1 Coding "Formation sanitaire et sociale préparant à un diplôme d’état délivré par l’administration sanitaire et sociale. Sont exclues les formations aux professions médicales préparées en université, hormis les formations et écoles de sages-femmes." "Formation sanitaire et sociale préparant à un diplôme d’état délivré par l’administration sanitaire et sociale. Sont exclues les formations aux professions médicales préparées en université, hormis les formations et écoles de sages-femmes."
* disciplineEnseignement from https://mos.esante.gouv.fr/NOS/TRE_R281-DisciplineEnseignement/FHIR/TRE-R281-DisciplineEnseignement?vs (preferred)
* modeFonctionnement 0..1 Coding "Le mode de fonctionnement précise la modalité d’accueil, d’hébergement et/ou d’ouverture de l’activité associée à la discipline (hébergement complet, externat, accueil de nuit, etc.). Par défaut, il est systématiquement renseigné avec la valeur 34 (Enseignement) provenant de la CodeSystem-TRE-R209-TypeActivite." "Le mode de fonctionnement précise la modalité d’accueil, d’hébergement et/ou d’ouverture de l’activité associée à la discipline (hébergement complet, externat, accueil de nuit, etc.). Par défaut, il est systématiquement renseigné avec la valeur 34 (Enseignement) provenant de la CodeSystem-TRE-R209-TypeActivite."
* modeFonctionnement from https://mos.esante.gouv.fr/NOS/TRE_R209-TypeActivite/FHIR/TRE-R209-TypeActivite?vs (preferred)
* dateAutorisation 0..1 date "Date de l’arrêté autorisant l’exercice de l’activité décrite." "Date de l’arrêté autorisant l’exercice de l’activité décrite."
* suppressionAutorisation 0..1 boolean "Indicateur de suppression de l'autorisation d’activité d’enseignement." "Indicateur de suppression de l'autorisation d’activité d’enseignement."
* EntiteGeographique 1..1 https://interop.esante.gouv.fr/ig/mos/StructureDefinition/EntiteGeographique "Lien vers la classe EntiteGeographique" "Lien vers la classe EntiteGeographique"