Logical: SituationOperationnelle
Id: SituationOperationnelle
* ^status = #draft
* . ^short = " Caractérise les conditions d'exercice du professionnel dans la mise en œuvre cadre de l’offre opérationnelle."
* . ^definition = " Caractérise les conditions d'exercice du professionnel dans la mise en œuvre cadre de l’offre opérationnelle."
* . ^type.code = "Element"
* identifiantSituationOperationnelle 0..1 Identifier " Identifiant de la situation opérationnelle, unique et persistant au niveau national, obtenu par l’association de l’identifiant de l’offre opérationnelle suivi du caractère « / » puis de l’identifiant du professionnel." " Identifiant de la situation opérationnelle, unique et persistant au niveau national, obtenu par l’association de l’identifiant de l’offre opérationnelle suivi du caractère « / » puis de l’identifiant du professionnel."
* modeExerciceOffre 0..1 Coding " Le mode d'exercice correspond au statut du professionnel lorsqu'il exerce dans le cadre de l'offre décrite." " Le mode d'exercice correspond au statut du professionnel lorsqu'il exerce dans le cadre de l'offre décrite."
* modeExerciceOffre from https://interop.esante.gouv.fr/ig/fhir/mos/ValueSet/ModeExercice-vs (preferred)
* competenceSpecifique 0..* Coding " La compétence spécifique correspond à une capacité ou connaissance reconnue qui permet ou facilite l’accueil d’une personne. La compétence spécifique n’est ni une spécialité ordinale, ni une profession." " La compétence spécifique correspond à une capacité ou connaissance reconnue qui permet ou facilite l’accueil d’une personne. La compétence spécifique n’est ni une spécialité ordinale, ni une profession."
* competenceSpecifique from https://interop.esante.gouv.fr/ig/fhir/mos/ValueSet/CompetenceSpecifique-vs (preferred)
* precisionHoraire 0..1 https://interop.esante.gouv.fr/ig/fhir/mos/StructureDefinition/Horaire " Décrit le planning d'activité du professionnel." " Décrit le planning d'activité du professionnel."
* secteurConventionnement 0..1 Coding " Secteur de conventionnement du professionnel libéral auquel il a adhéré auprès de l'Assurance Maladie." " Secteur de conventionnement du professionnel libéral auquel il a adhéré auprès de l'Assurance Maladie."
* secteurConventionnement from https://interop.esante.gouv.fr/ig/fhir/mos/ValueSet/CNAMAmeliSecteurConventionnement-vs (preferred)
* optionContratAccesAuxSoins 0..1 boolean " L'Option pratique tarifaire maîtrisée (OPTAM) a remplacé le Contrat d'accès aux soins (CAS) en 2017.L’Option pratique tarifaire maîtrisée (OPTAM) est un dispositif proposé par l’Assurance Maladie aux médecins conventionnés ayant pour objectif principal de faciliter l’accès aux soins en limitant, sans les supprimer, les dépassements d’honoraires.Les médecins exerçant une spécialité chirurgicale ou de chirurgie obstétrique, qui ont réalisé au moins 50 actes de chirurgie ou d'obstérique ont la possibilité d'adhérer à l'Option pratique tarifaire maîtrisée chirurgie et obstétrique (OPTAM-CO).Synonyme : optionPratiqueTarifaireMaîtrisée" " L'Option pratique tarifaire maîtrisée (OPTAM) a remplacé le Contrat d'accès aux soins (CAS) en 2017.L’Option pratique tarifaire maîtrisée (OPTAM) est un dispositif proposé par l’Assurance Maladie aux médecins conventionnés ayant pour objectif principal de faciliter l’accès aux soins en limitant, sans les supprimer, les dépassements d’honoraires.Les médecins exerçant une spécialité chirurgicale ou de chirurgie obstétrique, qui ont réalisé au moins 50 actes de chirurgie ou d'obstérique ont la possibilité d'adhérer à l'Option pratique tarifaire maîtrisée chirurgie et obstétrique (OPTAM-CO).Synonyme : optionPratiqueTarifaireMaîtrisée"
* carteVitaleAcceptee 0..1 boolean " L’indicateur Carte Vitale acceptée précise si le professionnel, dans le cadre de cette situation opérationnelle, dispose des moyens techniques pour prendre en charge la carte vitale ou pas. 0 : pas de prise en charge de la carte vitale1 : prise en charge de la carte vitale." " L’indicateur Carte Vitale acceptée précise si le professionnel, dans le cadre de cette situation opérationnelle, dispose des moyens techniques pour prendre en charge la carte vitale ou pas. 0 : pas de prise en charge de la carte vitale1 : prise en charge de la carte vitale."
* telecommunication 0..1 https://interop.esante.gouv.fr/ig/fhir/mos/StructureDefinition/Telecommunication " Adresse de télécommunication du professionnel dans le cadre de l'offre décrite." " Adresse de télécommunication du professionnel dans le cadre de l'offre décrite."